statuses/urls.py
from django.urls import path

from statuses import views

app_name = 'statuses'


urlpatterns = [
    path('', views.StatusListView.as_view(), name='statuses'),
    path('create/', views.StatusCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.StatusUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.StatusDeleteView.as_view(), name='delete'),
]

task_manager/statuses/urls.py
from django.urls import path

from task_manager.statuses import views

app_name = 'statuses'


urlpatterns = [
    path('', views.StatusListView.as_view(), name='statuses'),
    path('create/', views.StatusCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.StatusUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.StatusDeleteView.as_view(), name='delete'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import include, path

from task_manager.users.views import UserLoginView, UserLogoutView
from task_manager.views import IndexView

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('users/', include('task_manager.users.urls', namespace='users')),
    path('statuses/', include(
        'task_manager.statuses.urls',
        namespace='statuses')),
    path('tasks/', include('task_manager.tasks.urls', namespace='tasks')),
    path('labels/', include('task_manager.labels.urls', namespace='labels')),
]

tasks/urls.py
from django.urls import path

from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='tasks'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='detail'),
]

task_manager/statuses/models.py
from django.db import models


class Status(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Статус')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'status'
        verbose_name = 'Статуса'
        verbose_name_plural = 'Статусы'


# Create your models here.

statuses/forms.py
from django import forms
from django.utils.translation import gettext as _

from statuses.models import Status


class StatusCreateForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ('name',)

    name = forms.CharField(
        widget=forms.TextInput(attrs={
            "autofocus": True,
            'class': 'form-control',
            'placeholder': _('Name')}))


class StatusUpdateForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ('name',)

    name = forms.CharField(
        widget=forms.TextInput(attrs={
            "autofocus": True,
            'class': 'form-control',
            'placeholder': _('Name')}))

task_manager/statuses/forms.py
from django import forms
from django.utils.translation import gettext as _

from task_manager.statuses.models import Status


class StatusCreateForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ('name',)

    name = forms.CharField(
        widget=forms.TextInput(attrs={
            "autofocus": True,
            'class': 'form-control',
            'placeholder': _('Name')}))


class StatusUpdateForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ('name',)

    name = forms.CharField(
        widget=forms.TextInput(attrs={
            "autofocus": True,
            'class': 'form-control',
            'placeholder': _('Name')}))

statuses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from statuses.forms import StatusCreateForm, StatusUpdateForm
from statuses.mixins import PreventUsedStatusDeletionMixin
from statuses.models import Status


class StatusListView(LoginRequiredMixin, ListView):
    template_name = 'statuses/statuses.html'
    model = Status
    queryset = Status.objects.all().order_by('-id')
    context_object_name = 'statuses'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - statuses')
        return context


class StatusCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Status
    template_name = 'statuses/create.html'
    form_class = StatusCreateForm
    success_message = _('The status was created successfully')
    success_url = reverse_lazy('statuses:statuses')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - create status')
        context['status'] = True
        return context

    # def form_valid(self, form):
    #     return super().form_valid(form)


class StatusUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Status
    template_name = 'statuses/update.html'
    form_class = StatusUpdateForm
    success_url = reverse_lazy('statuses:statuses')
    success_message = _('Status successfully updated')
    # queryset = Status.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - update status info')
        # context['status'] = True
        return context


class StatusDeleteView(PreventUsedStatusDeletionMixin, SuccessMessageMixin, LoginRequiredMixin, DeleteView):

    model = Status
    success_url = reverse_lazy('statuses:statuses')
    template_name = 'statuses/delete.html'
    success_message = _('Status successfully deleted')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - delete status')
        return context


# Create your views here.

task_manager/statuses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from task_manager.statuses.forms import StatusCreateForm, StatusUpdateForm
from task_manager.statuses.mixins import PreventUsedStatusDeletionMixin
from task_manager.statuses.models import Status


class StatusListView(LoginRequiredMixin, ListView):
    template_name = 'statuses/statuses.html'
    model = Status
    queryset = Status.objects.all().order_by('-id')
    context_object_name = 'statuses'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - statuses')
        return context


class StatusCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Status
    template_name = 'statuses/create.html'
    form_class = StatusCreateForm
    success_message = _('The status was created successfully')
    success_url = reverse_lazy('statuses:statuses')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - create status')
        context['status'] = True
        return context


class StatusUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Status
    template_name = 'statuses/update.html'
    form_class = StatusUpdateForm
    success_url = reverse_lazy('statuses:statuses')
    success_message = _('Status successfully updated')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - update status info')
        return context


class StatusDeleteView(
    PreventUsedStatusDeletionMixin,
    SuccessMessageMixin,
    LoginRequiredMixin,
    DeleteView):

    model = Status
    success_url = reverse_lazy('statuses:statuses')
    template_name = 'statuses/delete.html'
    success_message = _('Status successfully deleted')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - delete status')
        return context


# Create your views here.

task_manager/statuses/templates/statuses/create.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <h1 class="mb-3">{% trans "Create status" %}</h1>
            <form method="post" class="card bg-light p-3">
                {% csrf_token %}
                <div class="mb-2">
                    <label class="mb-1" for="id_name">{% trans "Name" %}</label>
                    {{ form.name }}
                </div>
                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">{% trans "Create" %}</button>
                </div>
                {% if form.errors %}
                    <div class="alert alert-danger mt-2">
                        {% for field, errors in form.errors.items %}
                            {% for error in errors %}
                                {{ error }}
                            {% endfor %}
                        {% endfor %}
                    </div>
                    {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

task_manager/statuses/templates/statuses/delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <h1 class="mb-3">{% trans "Delete status" %}</h1>
            <p>{% trans "Are you sure, you want to delete status" %} "{{ status.name }}" ?</p>
            <form method="post" class="card p-3">
                {% csrf_token %}
                <div class="d-grid">
                    <button type="submit" class="btn btn-danger">{% trans "Yes, delete" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

task_manager/statuses/templates/statuses/statuses.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <h1 class="my-4">{% trans "Statuses" %}</h1>
            <div class="d-grid">
                    <a class="btn btn-primary w-25 mb-3" href="{% url "statuses:create" %}">{% trans "Create status" %}</a>
                </div>
                <table class="table table-striped table-hover table-bordered rounded-pill">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>{% trans "Name" %}</th>
                        <th>{% trans "Creation date" %}</th>
                        <th> </th>
                    </tr>
                    </thead>
                    {% for status in statuses %}
                    <tbody>
                    <tr>
                        <td>{{ status.id }}</td>
                        <td>{{ status.name }}</td>
                        <td>{{ status.created_at }}</td>
                        <td>
                            <a href="{% url "statuses:update" status.id %}">{% trans "Change" %}</a>
                            <br>
                            <a href="{% url "statuses:delete" status.id %}">{% trans "Delete" %}</a>
                        </td>
                    </tr>
                    </tbody>
                    {% endfor %}
                </table>
        </div>
    </div>
</div>
{% endblock %}

task_manager/statuses/templates/statuses/update.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <h1 class="mb-3">{% trans "Update status info" %}</h1>
            <form method="post" class="card bg-light p-3">
                {% csrf_token %}
                <div class="mb-2">
                    <label class="mb-1" for="id_name">{% trans "Name" %}</label>
                    {{ form.name }}
                </div>
                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">{% trans "Update" %}</button>
                </div>
                {% if form.errors %}
                    <div class="alert alert-danger mt-2">
                        {% for field, errors in form.errors.items %}
                            {% for error in errors %}
                                {{ error }}
                            {% endfor %}
                        {% endfor %}
                    </div>
                    {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}