labels/urls.py
from django.urls import path

from labels import views

app_name = 'labels'

urlpatterns = [
    path('', views.LabelListView.as_view(), name='labels'),
    path('create/', views.LabelCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.LabelUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.LabelDeleteView.as_view(), name='delete'),
]

task_manager/labels/urls.py
from django.urls import path

from task_manager.labels import views

app_name = 'labels'

urlpatterns = [
    path('', views.LabelListView.as_view(), name='labels'),
    path('create/', views.LabelCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.LabelUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.LabelDeleteView.as_view(), name='delete'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import include, path

from task_manager.users.views import UserLoginView, UserLogoutView
from task_manager.views import IndexView

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('users/', include('task_manager.users.urls', namespace='users')),
    path('statuses/', include(
        'task_manager.statuses.urls',
        namespace='statuses')),
    path('tasks/', include('task_manager.tasks.urls', namespace='tasks')),
    path('labels/', include('task_manager.labels.urls', namespace='labels')),
]

tasks/urls.py
from django.urls import path

from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='tasks'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='detail'),
]

task_manager/labels/models.py
from django.db import models


class Label(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Метка')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'labels'
        verbose_name = 'Метка'
        verbose_name_plural = 'Метки'
# Create your models here.

labels/forms.py
from django import forms
from django.utils.translation import gettext as _

from labels.models import Label


class LabelCreateForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = ('name',)

    name = forms.CharField(
        widget=forms.TextInput(attrs={
            "autofocus": True,
            'class': 'form-control',
            'placeholder': _('Name')}))


class LabelUpdateForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = ('name',)

    name = forms.CharField(
        widget=forms.TextInput(attrs={
            "autofocus": True,
            'class': 'form-control',
            'placeholder': _('Name')}))

task_manager/labels/forms.py
from django import forms
from django.utils.translation import gettext as _

from task_manager.labels.models import Label


class LabelCreateForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = ('name',)

    name = forms.CharField(
        widget=forms.TextInput(attrs={
            "autofocus": True,
            'class': 'form-control',
            'placeholder': _('Name')}))


class LabelUpdateForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = ('name',)

    name = forms.CharField(
        widget=forms.TextInput(attrs={
            "autofocus": True,
            'class': 'form-control',
            'placeholder': _('Name')}))

labels/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from labels.forms import LabelCreateForm, LabelUpdateForm
from labels.mixins import PreventUsedLabelsDeletionMixin
from labels.models import Label


class LabelListView(LoginRequiredMixin, ListView):
    template_name = 'labels/labels.html'
    model = Label
    queryset = Label.objects.all().order_by('-id')
    context_object_name = 'labels'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - labels')
        return context


class LabelCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Label
    template_name = 'labels/create.html'
    form_class = LabelCreateForm
    success_message = _('The label was created successfully')
    success_url = reverse_lazy('labels:labels')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - create label')
        context['label'] = True
        return context


class LabelUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Label
    template_name = 'labels/update.html'
    form_class = LabelUpdateForm
    success_url = reverse_lazy('labels:labels')
    success_message = _('Label successfully updated')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - update label info')
        # context['status'] = True
        return context


class LabelDeleteView(PreventUsedLabelsDeletionMixin, SuccessMessageMixin, LoginRequiredMixin, DeleteView):

    model = Label
    success_url = reverse_lazy('labels:labels')
    template_name = 'labels/delete.html'
    success_message = _('Label successfully deleted')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - delete label')
        return context

task_manager/labels/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from task_manager.labels.forms import LabelCreateForm, LabelUpdateForm
from task_manager.labels.mixins import PreventUsedLabelsDeletionMixin
from task_manager.labels.models import Label


class LabelListView(LoginRequiredMixin, ListView):
    template_name = 'labels/labels.html'
    model = Label
    queryset = Label.objects.all().order_by('-id')
    context_object_name = 'labels'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - labels')
        return context


class LabelCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Label
    template_name = 'labels/create.html'
    form_class = LabelCreateForm
    success_message = _('The label was created successfully')
    success_url = reverse_lazy('labels:labels')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - create label')
        context['label'] = True
        return context


class LabelUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Label
    template_name = 'labels/update.html'
    form_class = LabelUpdateForm
    success_url = '/labels/'
    success_message = _('Label successfully updated')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - update label info')
        context['label'] = True
        return context


class LabelDeleteView(
    PreventUsedLabelsDeletionMixin,
    SuccessMessageMixin,
    LoginRequiredMixin,
    DeleteView):

    model = Label
    success_url = reverse_lazy('labels:labels')
    template_name = 'labels/delete.html'
    success_message = _('Label successfully deleted')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - delete label')
        return context

task_manager/labels/templates/labels/create.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <h1 class="mb-3">{% trans "Create label" %}</h1>
            <form method="post" class="card bg-light p-3">
                {% csrf_token %}
                <div class="mb-2">
                    <label class="mb-1" for="id_name">{% trans "Name" %}</label>
                    {{ form.name }}
                </div>
                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">{% trans "Create" %}</button>
                </div>
                {% if form.errors %}
                    <div class="alert alert-danger mt-2">
                        {% for field, errors in form.errors.items %}
                            {% for error in errors %}
                                {{ error }}
                            {% endfor %}
                        {% endfor %}
                    </div>
                    {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

task_manager/labels/templates/labels/delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <h1 class="mb-3">{% trans "Delete label" %}</h1>
            <p>{% trans "Are you sure, you want to delete label" %} "{{ status.name }}" ?</p>
            <form method="post" class="card p-3">
                {% csrf_token %}
                <div class="d-grid">
                    <button type="submit" class="btn btn-danger">{% trans "Yes, delete" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

task_manager/labels/templates/labels/labels.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <h1 class="my-4">{% trans "Labels" %}</h1>
            <div class="d-grid">
                    <a class="btn btn-primary w-25 mb-3" href="{% url "labels:create" %}">{% trans "Create label" %}</a>
                </div>
                <table class="table table-striped table-hover table-bordered rounded-pill">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>{% trans "Name" %}</th>
                        <th>{% trans "Creation date" %}</th>
                        <th> </th>
                    </tr>
                    </thead>
                    {% for label in labels %}
                    <tbody>
                    <tr>
                        <td>{{ label.id }}</td>
                        <td>{{ label.name }}</td>
                        <td>{{ label.created_at }}</td>
                        <td>
                            <a href="{% url "labels:update" label.id %}">{% trans "Change" %}</a>
                            <br>
                            <a href="{% url "labels:delete" label.id %}">{% trans "Delete" %}</a>
                        </td>
                    </tr>
                    </tbody>
                    {% endfor %}
                </table>
        </div>
    </div>
</div>
{% endblock %}

task_manager/labels/templates/labels/update.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <h1 class="mb-3">{% trans "Update label" %}</h1>
            <form method="post" class="card bg-light p-3">
                {% csrf_token %}
                <div class="mb-2">
                    <label class="mb-1" for="id_name">{% trans "Name" %}</label>
                    {{ form.name }}
                </div>
                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">{% trans "Update" %}</button>
                </div>
                {% if form.errors %}
                    <div class="alert alert-danger mt-2">
                        {% for field, errors in form.errors.items %}
                            {% for error in errors %}
                                {{ error }}
                            {% endfor %}
                        {% endfor %}
                    </div>
                    {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}