task_manager/tasks/urls.py
from django.urls import path

from task_manager.tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='tasks'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='detail'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import include, path

from task_manager.users.views import UserLoginView, UserLogoutView
from task_manager.views import IndexView

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('users/', include('task_manager.users.urls', namespace='users')),
    path('statuses/', include(
        'task_manager.statuses.urls',
        namespace='statuses')),
    path('tasks/', include('task_manager.tasks.urls', namespace='tasks')),
    path('labels/', include('task_manager.labels.urls', namespace='labels')),
]

tasks/urls.py
from django.urls import path

from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='tasks'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='detail'),
]

task_manager/tasks/models.py
from django.db import models

from task_manager.labels.models import Label
from task_manager.statuses.models import Status
from task_manager.users.models import User


class Task(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(verbose_name='Описание задачи')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(
        to=User,
        on_delete=models.PROTECT,
        verbose_name='Создатель',
        related_name='created_tasks',
    )
    executor = models.ForeignKey(
        to=User,
        on_delete=models.PROTECT,
        verbose_name='Исполнитель',
        related_name='assigned_tasks',
        null=True,
        blank=True,
    )
    status = models.ForeignKey(
        to=Status,
        on_delete=models.PROTECT,
        verbose_name='Статус',
        related_name='tasks',
    )
    labels = models.ManyToManyField(
        to=Label,
        verbose_name='Метки',
        related_name='tasks_label',
        blank=True,
    )

    class Meta:
        db_table = 'tasks'
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    def __str__(self):
        return f"Задача {self.name} || Исполнитель {self.creator.username}"
# Create your models here.

task_manager/tasks/forms.py
from django import forms
from django.utils.translation import gettext as _

from task_manager.labels.models import Label
from task_manager.statuses.models import Status
from task_manager.tasks.models import Task
from task_manager.users.models import User


class TaskFilterForm(forms.Form):
    status = forms.ModelChoiceField(
        queryset=Status.objects.all(),
        required=False,
        label=_('Status'),
        widget=forms.Select(attrs={
            'class': 'form-control', }))

    executor = forms.ModelChoiceField(
        queryset=User.objects.all(),
        required=False,
        label=_('Executor'),
        widget=forms.Select(attrs={
            'class': 'form-control', }))

    my_tasks = forms.BooleanField(
        required=False,
        label=_('Only my tasks'),
        widget=forms.CheckboxInput(attrs={
            'class': 'form-check-input', }))

    labels = forms.ModelMultipleChoiceField(
        queryset=Label.objects.all(),
        required=False,
        label=_('Label'),
        widget=forms.SelectMultiple(attrs={
            'class': 'form-select',
            'size': '5'}))


class TaskCreateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'description', 'status', 'executor', 'labels',)

    name = forms.CharField(
        widget=forms.TextInput(attrs={
            "autofocus": True,
            'class': 'form-control',
            'placeholder': _('Name')}))

    description = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': _('Description')}))

    status = forms.ModelChoiceField(
        queryset=Status.objects.all(),
        label=_('Status'),
        widget=forms.Select(attrs={
            'class': 'form-control', }))

    executor = forms.ModelChoiceField(
        queryset=User.objects.all(),
        required=False,
        label=_('Executor'),
        widget=forms.Select(attrs={
            'class': 'form-control', }))

    labels = forms.ModelMultipleChoiceField(
        queryset=Label.objects.all(),
        required=False,
        label=_('Label'),
        widget=forms.SelectMultiple(attrs={
            'class': 'form-select',
            'size': '5'}))


class TaskUpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'description', 'status', 'executor', 'labels',)

    name = forms.CharField(
        widget=forms.TextInput(attrs={
            "autofocus": True,
            'class': 'form-control',
            'placeholder': _('Name')}))

    description = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': _('Description of task')}))

    status = forms.ModelChoiceField(
        queryset=Status.objects.all(),
        label=_('Status'),
        widget=forms.Select(attrs={
            'class': 'form-control', }))

    executor = forms.ModelChoiceField(
        queryset=User.objects.all(),
        required=False,
        label=_('Executor'),
        widget=forms.Select(attrs={
            'class': 'form-control', }))

    labels = forms.ModelMultipleChoiceField(
        queryset=Label.objects.all(),
        required=False,
        label=_('Label'),
        widget=forms.SelectMultiple(attrs={
            'class': 'form-select',
            'size': '5'}))

tasks/forms.py
from django import forms
from django.utils.translation import gettext as _

from labels.models import Label
from statuses.models import Status
from tasks.models import Task
from users.models import User


class TaskFilterForm(forms.Form):
    status = forms.ModelChoiceField(
        queryset=Status.objects.all(),
        required=False,
        label=_('Status'),
        widget=forms.Select(attrs={
            'class': 'form-control', }))

    executor = forms.ModelChoiceField(
        queryset=User.objects.all(),
        required=False,
        label=_('Executor'),
        widget=forms.Select(attrs={
            'class': 'form-control', }))

    my_tasks = forms.BooleanField(
        required=False,
        label=_('Only my tasks'),
        widget=forms.CheckboxInput(attrs={
            'class': 'form-check-input', }))

    label = forms.ModelMultipleChoiceField(
        queryset=Label.objects.all(),
        required=False,
        label=_('Label'),
        widget=forms.SelectMultiple(attrs={
            'class': 'form-select',
            'size': '5'}))


class TaskCreateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'description', 'status', 'executor', 'label',)

    title = forms.CharField(
        widget=forms.TextInput(attrs={
            "autofocus": True,
            'class': 'form-control',
            'placeholder': _('Name')}))

    description = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Name')}))

    status = forms.ModelChoiceField(
        queryset=Status.objects.all(),
        required=False,
        label=_('Status'),
        widget=forms.Select(attrs={
            'class': 'form-control', }))

    executor = forms.ModelChoiceField(
        queryset=User.objects.all(),
        required=False,
        label=_('Executor'),
        widget=forms.Select(attrs={
            'class': 'form-control', }))

    label = forms.ModelMultipleChoiceField(
        queryset=Label.objects.all(),
        required=False,
        label=_('Label'),
        widget=forms.SelectMultiple(attrs={
            'class': 'form-select',
            'size': '5'}))


class TaskUpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'description', 'status', 'executor', 'label',)

    title = forms.CharField(
        widget=forms.TextInput(attrs={
            "autofocus": True,
            'class': 'form-control',
            'placeholder': _('Name')}))

    description = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Name')}))

    status = forms.ModelChoiceField(
        queryset=Status.objects.all(),
        required=False,
        label=_('Status'),
        widget=forms.Select(attrs={
            'class': 'form-control', }))

    executor = forms.ModelChoiceField(
        queryset=User.objects.all(),
        required=False,
        label=_('Executor'),
        widget=forms.Select(attrs={
            'class': 'form-control', }))

    label = forms.ModelMultipleChoiceField(
        queryset=Label.objects.all(),
        widget=forms.CheckboxSelectMultiple(
            attrs={'class': 'checkbox-container'}))

task_manager/tasks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from task_manager.tasks.forms import (
    TaskCreateForm,
    TaskFilterForm,
    TaskUpdateForm,
)
from task_manager.tasks.mixins import UserTaskPermissionMixin
from task_manager.tasks.models import Task


class TaskListView(LoginRequiredMixin, ListView):

    template_name = 'tasks/tasks.html'
    model = Task
    context_object_name = 'tasks'

    def get_queryset(self):

        status = self.request.GET.get('status')
        executor = self.request.GET.get('executor')
        labels = self.request.GET.get('labels')
        my_tasks = self.request.GET.get('my_tasks')

        tasks = Task.objects.all().order_by('-id')  # базовый queryset

        if status:  # если выбран статус
            tasks = tasks.filter(status_id=status)
        if executor:  # если выбран исполнитель
            tasks = tasks.filter(executor_id=executor)
        if labels:
            tasks = tasks.filter(labels=labels)
        if my_tasks == 'on':  # если выбрана опция "только мои задачи"
            tasks = tasks.filter(creator=self.request.user)

        return tasks

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_form'] = TaskFilterForm(self.request.GET)
        context['title'] = _('Task manager - tasks')
        return context


class TaskCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):

    model = Task
    template_name = 'tasks/create.html'
    form_class = TaskCreateForm
    success_message = _('The task was created successfully')
    success_url = reverse_lazy('tasks:tasks')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - create task')
        context['task'] = True
        return context

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)


class TaskUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):

    model = Task
    template_name = 'tasks/update.html'
    form_class = TaskUpdateForm
    success_message = _('The task was updated successfully')
    success_url = reverse_lazy('tasks:tasks')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - update task')
        context['task'] = True
        return context


class TaskDetailView(LoginRequiredMixin, DetailView):

    model = Task
    template_name = 'tasks/task.html'
    context_object_name = "task"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - detail view of task')
        return context


class TaskDeleteView(SuccessMessageMixin, UserTaskPermissionMixin, DeleteView):

    model = Task
    success_url = '/tasks/'
    template_name = 'tasks/delete.html'
    success_message = _('Task successfully deleted')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - delete task')
        return context


# Create your views here.

tasks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from tasks.forms import TaskCreateForm, TaskFilterForm, TaskUpdateForm
from tasks.mixins import UserTaskPermissionMixin
from tasks.models import Task


class TaskListView(LoginRequiredMixin, ListView):

    template_name = 'tasks/tasks.html'
    model = Task
    context_object_name = 'tasks'

    def get_queryset(self):

        status = self.request.GET.get('status')
        executor = self.request.GET.get('executor')
        label = self.request.GET.get('label')
        my_tasks = self.request.GET.get('my_tasks')

        tasks = Task.objects.all().order_by('-id')  # базовый queryset

        if status:  # если выбран статус
            tasks = tasks.filter(status_id=status)
        if executor:  # если выбран исполнитель
            tasks = tasks.filter(executor_id=executor)
        if label:
            tasks = tasks.filter(label=label)
        if my_tasks == 'on':  # если выбрана опция "только мои задачи"
            tasks = tasks.filter(creator=self.request.user)

        return tasks

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_form'] = TaskFilterForm(self.request.GET)
        context['title'] = _('Task manager - tasks')
        return context


class TaskCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):

    model = Task
    template_name = 'tasks/create.html'
    form_class = TaskCreateForm
    success_message = _('The task was created successfully')
    success_url = reverse_lazy('tasks:tasks')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - create task')
        context['task'] = True
        return context

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)


class TaskUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):

    model = Task
    template_name = 'tasks/update.html'
    form_class = TaskUpdateForm
    success_message = _('The task was updated successfully')
    success_url = reverse_lazy('tasks:tasks')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - update task')
        context['task'] = True
        return context


class TaskDetailView(LoginRequiredMixin, DetailView):

    model = Task
    template_name = 'tasks/task.html'
    context_object_name = "task"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - detail view of task')
        return context


class TaskDeleteView(SuccessMessageMixin, UserTaskPermissionMixin, DeleteView):

    model = Task
    success_url = reverse_lazy('tasks:tasks')
    template_name = 'tasks/delete.html'
    success_message = _('Task successfully deleted')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - delete task')
        return context


# Create your views here.

task_manager/tasks/templates/tasks/create.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <h1 class="mb-3">{% trans "Create task" %}</h1>
            <form method="post" class="card bg-light p-3">
                {% csrf_token %}
                <div class="mb-2">
                    <label class="mb-1" for="id_name">{% trans "Name" %}</label>
                    {{ form.name }}
                </div>
                <div class="mb-2">
                    <label class="mb-1" for="id_description">{% trans "Description of task" %}</label>
                    {{ form.description }}
                </div>
                <div class="mb-2">
                    <label class="mb-1" for="id_status">{% trans "Status" %}</label>
                    {{ form.status }}
                </div>
                <div class="mb-2">
                    <label class="mb-1" for="id_executor">{% trans "Executor" %}</label>
                    {{ form.executor }}
                </div>
                <div class="mb-2">
                    <label class="mb-1" for="id_labels">{% trans "Labels" %}</label>
                    {{ form.labels }}
                </div>
                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">{% trans "Create" %}</button>
                </div>
                {% if form.errors %}
                    <div class="alert alert-danger mt-2">
                        {% for field, errors in form.errors.items %}
                            {% for error in errors %}
                                {{ error }}
                            {% endfor %}
                        {% endfor %}
                    </div>
                    {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

task_manager/tasks/templates/tasks/delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <h1 class="mb-3">{% trans "Delete task!" %}</h1>
            <p>{% trans "Are you sure, you want to delete task" %} {{ task.name }} ?</p>
            <form method="post" class="card p-3">
                {% csrf_token %}
                <div class="d-grid">
                    <button type="submit" class="btn btn-danger">{% trans "Yes, delete" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

task_manager/tasks/templates/tasks/task.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <div class="card bg-primary text-white p-3">
                <div class="mb-2">
                    <h3>{{ task.name }}</h3>
                </div>
            </div>
            <div class="card bg-light p-3 mt-3">
                <div class="mb-2">
                    <h5>{{ task.description }}</h5>
                </div>
                <hr>
                <div class="mb-2">
                    <p>{% trans "Creator" %}: {{ task.creator }}</p>
                </div>
                <div class="mb-2">
                    <p>{% trans "Executor" %}: {{ task.executor }}</p>
                </div>
                <div class="mb-2">
                    <p>{% trans "Status" %}: {{ task.status }}</p>
                </div>
                <div class="mb-2">
                    <p>{% trans "Labels" %}:
                        {% for label in task.labels.all %}
                        <ul>
                            <li>{{ label.name }}</li>
                        </ul>
                        {% endfor %}
                    </p>
                </div>
                <div class="mb-2">
                   <a class="mt-2 btn btn-primary w-25" href="{% url "tasks:update" task.id %}">{% trans "Change" %}</a>
                            <br>
                    <a class="mt-2 btn btn-danger w-25" href="#">{% trans "Delete" %}</a>
                </div>

            </div>

        </div>
    </div>
</div>
{% endblock %}

task_manager/tasks/templates/tasks/tasks.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <h1 class="mb-3">{% trans "Tasks" %}</h1>
            <div class="d-grid">
                    <a class="btn btn-primary w-25 mb-3" href="{% url "tasks:create" %}">{% trans "Create task" %}</a>
                </div>
            <form method="get" class="card p-3 bg-light">
                {% csrf_token %}
                <div class="mb-2">
                    <label class="mb-1" for="id_status">{% trans "Status" %}</label>
                    {{ filter_form.status }}
                </div>
                <div class="mb-2">
                    <label class="mb-1" for="id_executor">{% trans "Executor" %}</label>
                    {{ filter_form.executor }}
                </div>
                <div class="mb-2">
                    <label class="mb-1" for="id_labels">{% trans "Label" %}</label>
                    {{ filter_form.labels }}
                </div>
                <div class="mb-2">
                    <label class="mb-1" for="id_my_tasks">{% trans "Only your own tasks" %}</label>
                    {{ filter_form.my_tasks }}
                </div>
                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">{% trans "Show" %}</button>
                </div>
            </form>
            <table class="table table-striped table-hover table-bordered rounded-pill mt-2">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>{% trans "Name" %}</th>
                        <th>{% trans "Status" %}</th>
                        <th>{% trans "Author" %}</th>
                        <th>{% trans "Executor" %}</th>
                        <th>{% trans "Creation date" %}</th>
                        <th> </th>
                    </tr>
                    </thead>
                    {% for task in tasks %}
                    <tbody>
                    <tr>
                        <td>{{ task.id }}</td>
                        <td>
                            <a href="{% url "tasks:detail" task.id %}">{{ task.name }}</a>
                        </td>
                        <td>{{ task.status }}</td>
                        <td>{{ task.creator.first_name }} {{ task.creator.last_name }}</td>
                        <td>{{ task.executor.first_name }} {{ task.executor.last_name }}</td>
                        <td>{{ task.created_at }}</td>
                        <td>
                            <a href="{% url "tasks:update" task.id %}">{% trans "Change" %}</a>
                            <br>
                            <a href="{% url "tasks:delete" task.id %}">{% trans "Delete" %}</a>
                        </td>
                    </tr>
                    </tbody>
                    {% endfor %}
                </table>
        </div>
    </div>
</div>

{% endblock %}

task_manager/tasks/templates/tasks/update.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <h1 class="mb-3">{% trans "Update task" %}</h1>
            <form method="post" class="card bg-light p-3">
                {% csrf_token %}
                 <div class="mb-2">
                    <label class="mb-1" for="id_name">{% trans "Name" %}</label>
                    {{ form.name }}
                </div>
                <div class="mb-2">
                    <label class="mb-1" for="id_description">{% trans "Description" %}</label>
                    {{ form.description }}
                </div>
                <div class="mb-2">
                    <label class="mb-1" for="id_status">{% trans "Status" %}</label>
                    {{ form.status }}
                </div>
                <div class="mb-2">
                    <label class="mb-1" for="id_executor">{% trans "Executor" %}</label>
                    {{ form.executor }}
                </div>
                <div class="mb-2">
                    <label class="mb-1" for="id_labels">{% trans "Labels" %}</label>
                    {{ form.labels }}
                </div>
                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">{% trans "Update" %}</button>
                </div>
                {% if form.errors %}
                    <div class="alert alert-danger mt-2">
                        {% for field, errors in form.errors.items %}
                            {% for error in errors %}
                                {{ error }}
                            {% endfor %}
                        {% endfor %}
                    </div>
                    {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}