task_manager/urls.py
from django.contrib import admin
from django.urls import include, path

from task_manager.users.views import UserLoginView, UserLogoutView
from task_manager.views import IndexView

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('users/', include('task_manager.users.urls', namespace='users')),
    path('statuses/', include(
        'task_manager.statuses.urls',
        namespace='statuses')),
    path('tasks/', include('task_manager.tasks.urls', namespace='tasks')),
    path('labels/', include('task_manager.labels.urls', namespace='labels')),
]

task_manager/users/urls.py
from django.urls import path

from task_manager.users import views

app_name = 'users'


urlpatterns = [
    path('', views.UserListView.as_view(), name='users'),
    path('create/', views.UserCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='delete'),
]

tasks/urls.py
from django.urls import path

from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='tasks'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='detail'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'


urlpatterns = [
    path('', views.UserListView.as_view(), name='users'),
    path('create/', views.UserCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='delete'),
]

task_manager/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.get_full_name()


# Create your models here.

task_manager/users/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserChangeForm,
    UserCreationForm,
)
from django.utils.translation import gettext as _

from task_manager.users.models import User


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(
        label=_('Username'),
        widget=forms.TextInput(attrs={
            "autofocus": True,
            'class': 'form-control',
            'placeholder': _('Username')}))
    password = forms.CharField(
        label=_('Password'),
        widget=forms.PasswordInput(attrs={
            "autocomplete": "current-password",
            'class': "form-control",
            'placeholder': _('Password')}))

    class Meta:
        model = User
        fields = ['username', 'password']


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "password1",
            "password2",
        )

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Enter your first name')})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Enter your last name')})
    )
    username = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Enter your login')}))
    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': "form-control",
            'placeholder': _('Enter your password')})
    )
    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            "autocomplete": "current-password",
            'class': "form-control",
            'placeholder': _('Repeat your password')})
    )


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "password1",
            "password2",
        )

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Enter your first name')})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Enter your last name')})
    )
    username = forms.CharField(
        # required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Enter your login')}))
    password1 = forms.CharField(
        required=False,
        widget=forms.PasswordInput(attrs={
            'class': "form-control",
            'placeholder': _('Enter your password')})
    )
    password2 = forms.CharField(
        required=False,
        widget=forms.PasswordInput(attrs={
            "autocomplete": "current-password",
            'class': "form-control",
            'placeholder': _('Repeat your password')})
    )

users/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserChangeForm,
    UserCreationForm,
)
from django.utils.translation import gettext as _

from users.models import User


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(
        widget=forms.TextInput(attrs={
            "autofocus": True,
            'class': 'form-control',
            'placeholder': _('Enter your login')}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            "autocomplete": "current-password",
            'class': "form-control",
            'placeholder': _('Enter your password')}))

    class Meta:
        model = User
        fields = ['username', 'password']


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "password1",
            "password2",
        )

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Enter your first name')})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Enter your last name')})
    )
    username = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Enter your login')}))
    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': "form-control",
            'placeholder': _('Enter your password')})
    )
    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            "autocomplete": "current-password",
            'class': "form-control",
            'placeholder': _('Repeat your password')})
    )


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "password1",
            "password2",
        )

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Enter your first name')})
    )
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Enter your last name')})
    )
    username = forms.CharField(
        # required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('Enter your login')}))
    password1 = forms.CharField(
        required=False,
        widget=forms.PasswordInput(attrs={
            'class': "form-control",
            'placeholder': _('Enter your password')})
    )
    password2 = forms.CharField(
        # required=Fal
        required=False,
        widget=forms.PasswordInput(attrs={
            "autocomplete": "current-password",
            'class': "form-control",
            'placeholder': _('Repeat your password')})
    )

task_manager/users/views.py
from django.contrib import auth, messages
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from task_manager.tasks.models import Task
from task_manager.users.forms import (
    UserLoginForm,
    UserRegistrationForm,
    UserUpdateForm,
)
from task_manager.users.mixins import (
    PreventUsedUserDeletionMixin,
    UserPermissionMixin,
)
from task_manager.users.models import User


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    success_url = 'index'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - authorization')
        return context

    def form_valid(self, form):
        message = _('You are logged in to your account')
        user = form.get_user()
        """Security check complete. Log the user in."""
        auth.login(self.request, user)
        messages.success(self.request, f"{message}")
        return HttpResponseRedirect(self.get_success_url())


class UserCreateView(SuccessMessageMixin, CreateView):
    template_name = 'users/create.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('login')
    success_message = _('You have successfully registered!')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - registration')
        return context


class UserUpdateView(UserPermissionMixin, UpdateView):
    model = User
    template_name = 'users/update.html'
    form_class = UserUpdateForm
    success_url = reverse_lazy('users:users')

    def form_valid(self, form):
        messages.success(self.request, _('User info was updated'))
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _('User info update error.'))
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        user = self.object
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - update user info')
        context['user_tasks'] = Task.objects.filter(creator=user)
        context['user_as_executor_tasks'] = Task.objects.filter(executor=user)
        return context


class UserDeleteView(
    PreventUsedUserDeletionMixin,
    SuccessMessageMixin,
    UserPermissionMixin,
    DeleteView
):
    model = User
    success_url = reverse_lazy('users:users')
    template_name = 'users/delete.html'
    success_message = _('User successfully deleted')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - delete user')
        return context


class UserListView(ListView):

    template_name = 'users/users.html'
    model = User
    queryset = User.objects.all().order_by('-id')
    context_object_name = 'users'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - users')
        return context


class UserLogoutView(LoginView):

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            logout(request)
            messages.info(request, _('You are logged out'))
        return redirect('index')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - logout')
        return context

users/views.py
from django.contrib import auth, messages
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from users.forms import UserLoginForm, UserRegistrationForm, UserUpdateForm
from users.mixins import UserPermissionMixin
from users.models import User


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    success_url = 'index'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - authorization')
        return context

    def form_valid(self, form):
        message = _('You are logged in to your account')
        user = form.get_user()
        """Security check complete. Log the user in."""
        auth.login(self.request, user)
        messages.success(self.request, f"{user.username}, {message}")
        return HttpResponseRedirect(self.get_success_url())


class UserCreateView(SuccessMessageMixin, CreateView):
    template_name = 'users/create.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('login')
    success_message = _('You have successfully registered!')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - registration')
        return context


class UserUpdateView(UserPermissionMixin, UpdateView):
    model = User
    template_name = 'users/update.html'
    form_class = UserUpdateForm
    success_url = reverse_lazy('users:users')

    # УДАЛЕНО переопределение get_object - теперь используем стандартное получение объекта

    def form_valid(self, form):
        messages.success(self.request, _('User info was updated'))
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _('User info update error.'))
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Task manager - update user info')
        return context


class UserDeleteView(UserPermissionMixin, DeleteView):
    model = User
    success_url = reverse_lazy('index')
    template_name = 'users/delete.html'
    success_message = _('User successfully deleted')

    def delete(self, request, *args, **kwargs):
        messages.success(request, self.success_message)
        return super().delete(request, *args, **kwargs)


# class UserUpdateView(UserPermissionMixin, UpdateView):
#     model = User
#
#     template_name = 'users/update.html'
#     form_class = UserUpdateForm
#     success_url = reverse_lazy('users:users')
#
#
#     def get_object(self, queryset=None):
#         return self.request.user
#
#     def form_valid(self, form):
#         message = _('User info was updated')
#         messages.success(self.request, message)
#         return super().form_valid(form)
#
#     def form_invalid(self, form):
#         message = _('User info update error.')
#         messages.error(self.request, message)
#         return super().form_invalid(form)
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['title'] = _('Task manager - update user info')
#         return context
#
#
# class UserDeleteView(UserPermissionMixin, SuccessMessageMixin, DeleteView):
#
#     model = User
#     success_url = reverse_lazy('index')
#     template_name = 'users/delete.html'
#     success_message = _('User successfully deleted')
#
#
class UserListView(ListView):
    template_name = 'users/users.html'
    model = User
    queryset = User.objects.all().order_by('-id')
    context_object_name = 'users'


class UserLogoutView(LoginView):

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            logout(request)
            messages.info(request, _('You are logged out'))
        return redirect('index')

# @login_required
# def logout(request):
#     message = _('You have successfully logged out of your account')
#     messages.success(request, f"{request.user.username}, {message}")
#     auth.logout(request)
#     return redirect(reverse('index'))
# # Create your views here.

task_manager/users/templates/users/create.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <h1 class="mb-3">{% trans "Registration" %}</h1>
            <form method="post" class="card bg-light p-3">
                {% csrf_token %}

                <div class="mb-2">
                    <label class="mb-1" for="id_first_name">{% trans "Name" %}</label>
                    {{ form.first_name }}
                </div>

                <div class="mb-2">
                    <label class="form-label mb-1" for="id_last_name">{% trans "Surname" %}</label>
                    {{ form.last_name }}
                </div>

                <div class="mb-2">
                    <label class="form-label mb-1" for="id_username">{% trans "Имя пользователя" %}</label>
                    {{ form.username }}
                    <div class="form-text small mt-0">
                        {% trans "* Required field. No more than 150 characters. Only letters, numbers, and symbols @/./+/-/_." %}
                    </div>
                    </div>

                <div class="mb-2">
                    <label class="form-label mb-1" for="id_password1">{% trans "Password" %}</label>
                    {{ form.password1 }}
                    <div class="form-text small mt-0">
                        {% trans "* Your password must contain at least 3 characters." %}
                    </div>
                </div>

                <div class="mb-3">
                    <label class="form-label mb-1" for="id_password2">{% trans "Password confirmation" %}</label>
                    {{ form.password2 }}
                    <div class="form-text small mt-0">
                        {% trans "* Please repeat the password again" %}
                    </div>
                </div>

                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">{% trans "Register" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

task_manager/users/templates/users/delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <h1 class="mb-3">{% trans "Delete user" %}</h1>
            <form method="post" class="card bg-light p-3">
                {% csrf_token %}
                <p>{% trans "Are you sure you want delete" %} {{ user.first_name }} {{ user.last_name }} ?</p>
                <div class="d-grid">
                    <button type="submit" class="btn btn-danger">{% trans "Yes, delete" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

task_manager/users/templates/users/login.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <h1 class="my-4">{% trans "Login" %}</h1>
            <form method="post" class="card bg-light p-3">
                {% csrf_token %}

                <div class="mb-3">
                    <label class="form-label" for="id_username">{% trans "Username" %}</label>
                    {{ form.username }}
                </div>

                <div class="mb-3">
                    <label class="form-label" for="id_password">{% trans "Password" %}</label>
                    {{ form.password }}
                </div>

                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">{% trans "Enter" %}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

task_manager/users/templates/users/update.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <h1 class="mb-3">{% trans "Update user info" %}</h1>
            <form method="post" class="card bg-light p-3">
                {% csrf_token %}

                <div class="mb-2">
                    <label class="mb-1" for="id_first_name">{% trans "Name" %}</label>
                    {{ form.first_name }}
                </div>

                <div class="mb-2">
                    <label class="form-label mb-1" for="id_last_name">{% trans "Surname" %}</label>
                    {{ form.last_name }}
                </div>

                <div class="mb-2">
                    <label class="form-label mb-1" for="id_username">{% trans "Имя пользователя" %}</label>
                    {{ form.username }}
                    <div class="form-text small mt-0">
                        {% trans "* Required field. No more than 150 characters. Only letters, numbers, and symbols @/./+/-/_." %}
                    </div>
                    </div>

                <div class="mb-2">
                    <label class="form-label mb-1" for="id_password1">{% trans "Password" %}</label>
                    {{ form.password1 }}
                    <div class="form-text small mt-0">
                        {% trans "* Your password must contain at least 3 characters." %}
                    </div>
                </div>

                <div class="mb-3">
                    <label class="form-label mb-1" for="id_password2">{% trans "Password confirmation" %}</label>
                    {{ form.password2 }}
                    <div class="form-text small mt-0">
                        {% trans "* Please repeat the password again" %}
                    </div>
                </div>

                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">{% trans "Update info" %}</button>
                </div>
            </form>
            <div class="user-tasks" style="margin-top: 30px;">
        <h3>{% trans "User's tasks" %}:</h3>

        {% if user_tasks %}
            <ul>
                {% for task in user_tasks %}
                    <li>
                        <a href="{% url "tasks:detail" task.id %}">{{ task.name }}</a>
                        ({% trans "Status" %}: {{ task.status }})
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>{% trans "No tasks found" %}.</p>
        {% endif %}
    </div>
            <div class="user-tasks" style="margin-top: 30px;">
        <h3>{% trans "Tasks where user is executor" %}:</h3>

        {% if user_as_executor_tasks %}
            <ul>
                {% for task in user_as_executor_tasks %}
                    <li>
                        <a href="{% url "tasks:detail" task.id %}">{{ task.name }}</a>
                        ({% trans "Status" %}: {{ task.status }})
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>{% trans "No tasks found" %}.</p>
        {% endif %}
    </div>
        </div>
    </div>
</div>
{% endblock %}

task_manager/users/templates/users/users.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="custom-form-container col-12 col-lg-10 p-4">
            <h1 class="my-4">{% trans "Users" %}</h1>
                <table class="table table-striped table-hover table-bordered rounded-pill">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>{% trans "Username" %}</th>
                        <th>{% trans "Full name" %}</th>
                        <th>{% trans "Creation date" %}</th>
                        <th> </th>
                    </tr>
                    </thead>
                    {% for user in users %}
                    <tbody>
                    <tr>
                        <td>{{ user.id }}</td>
                        <td>{{ user.username }}</td>
                        <td>{{ user.first_name }} {{ user.last_name }}</td>
                        <td>{{ user.date_joined }}</td>
                        <td>
                            <a href="{% url "users:update" user.id %}">{% trans "Change" %}</a>
                            <br>
                            <a href="{% url "users:delete" user.id %}">{% trans "Delete" %}</a>
                        </td>
                    </tr>
                    </tbody>
                    {% endfor %}
                </table>
        </div>
    </div>
</div>
{% endblock %}